services:
  test_studio_backend:
    image: test_studio_backend
    container_name: test_studio_backend
    build:
      context: .
      dockerfile: studio/config/docker/Dockerfile.test
    environment:
      PYTHONPATH: .
      TZ: Asia/Tokyo
      STRIPE_CALLBACK_URL: http://localhost:8000
      STRIPE_SECRET_KEY: sk_test_dummy_123
      STRIPE_WEBHOOK_SECRET: whsec_dummy_123
    volumes:
      - .:/app

  test_studio_frontend:
    image: test_studio_frontend
    container_name: test_studio_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    environment:
      TZ: Asia/Tokyo
    command: yarn test:ci
