from studio.app.common.core.snakemake.smk_utils import SmkUtils
from studio.app.common.core.snakemake.snakemake_reader import SmkConfigReader
from studio.app.common.core.utils.filepath_creater import join_filepath
from studio.app.common.core.workflow.workflow import ProcessType
from studio.app.dir_path import DIRPATH

from studio.app.common.core.workflow.workflow import NodeType, NodeTypeUtil
from studio.app.common.core.mode import MODE

if MODE.IN_SNAKEMAKE_BATCH:
    _config_path = SmkConfigReader.get_batch_config_path()
else:
    _config_path = "snakemake.yaml"

configfile: _config_path

# Compute paths outside rule definition to avoid Snakemake parsing issues
all_outputs = [
    SmkUtils._make_relative_path(join_filepath([DIRPATH.OUTPUT_DIR, x]))
    for x in config["last_output"]
]

rule all:
    input: all_outputs

for rule_name, details in config["rules"].items():
    # make rules of input node
    if NodeTypeUtil.check_nodetype_from_filetype(details["type"]) == NodeType.DATA:
        rule:
            name:
                rule_name
            input:
                SmkUtils.input(details)
            output:
                SmkUtils.output(details)
            params:
                name = details
            script:
                f"{DIRPATH.APP_DIR}/common/core/rules/data.py"

    # make rule of post_process
    elif details["type"] in [
        ProcessType.POST_PROCESS.type,
    ]:
        rule:
            name:
                rule_name
            input:
                SmkUtils.input(details)
            output:
                SmkUtils.output(details)
            params:
                name = details
            script:
                f"{DIRPATH.APP_DIR}/common/core/rules/post_process.py"

    # make rules of algo node
    else:
        rule:
            name:
                rule_name
            input:
                SmkUtils.input(details)
            output:
                SmkUtils.output(details)
            params:
                name = details
            conda:
                SmkUtils.conda(details)
            script:
                f"{DIRPATH.APP_DIR}/common/core/rules/func.py"
