"""
Secure Routing Middleware

This middleware generates cryptographically signed routing tokens for authenticated
users to prevent header spoofing attacks on ALB routing. The tokens use HMAC-SHA256
signatures that can only be generated by the backend with the secret key.

Security Features:
- HMAC-SHA256 signed tokens prevent forgery without secret key
- Timestamp validation prevents replay attacks (5-minute window)
- Backend-controlled routing eliminates client-controlled header vulnerability
- Integrates with AWS Secrets Manager for secure key storage

Architecture:
1. Extract authenticated user from request state
2. Generate HMAC-signed token: base64(uid|tier|timestamp|signature)
3. Add X-Routing-Token header to response
4. Frontend includes token in subsequent requests
5. ALB routing rules use verified tokens
"""

import asyncio
import base64
import hashlib
import hmac
import json
import os
import threading
import time
from datetime import datetime
from typing import Optional

import boto3
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from studio.app.common.core.logger import AppLogger
from studio.app.common.core.mode import MODE

logger = AppLogger.get_logger()

# Global cache for HMAC secret key
_secret_key_cache = {"key": None, "timestamp": 0, "lock": threading.Lock()}
_SECRET_CACHE_TTL = 300  # 5 minutes

# Token expiration window (5 minutes)
_TOKEN_TTL_SECONDS = 300


class SecureRoutingMiddleware:
    """
    ASGI Middleware to generate HMAC-signed routing tokens for authenticated users.

    This middleware:
    - Extracts authenticated user from request state (set by auth dependencies)
    - Generates HMAC-SHA256 signed routing token with uid, tier, and timestamp
    - Adds X-Routing-Token header to responses
    - Caches secret key from AWS Secrets Manager
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app
        self.secret_name = os.environ.get(
            "ROUTING_HMAC_SECRET_NAME", "subscr-premium-routing-hmac-key"
        )
        self.aws_region = os.environ.get("AWS_DEFAULT_REGION", "ap-northeast-1")

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            # Skip non-HTTP requests (e.g., websocket, lifespan)
            await self.app(scope, receive, send)
            return

        # Skip in standalone mode
        if MODE.IS_STANDALONE:
            await self.app(scope, receive, send)
            return

        # Get request path
        path = scope.get("path", "")

        # Skip health check and auth endpoints to avoid overhead
        if path in ["/health", "/api/auth/login", "/api/auth/refresh"]:
            await self.app(scope, receive, send)
            return

        # Flag to track if we've already added the header
        has_added_token = False

        async def send_wrapper(message: Message) -> None:
            """
            Wrap the send function to intercept response headers.
            When response headers are sent, add the X-Routing-Token header.
            """
            nonlocal has_added_token

            # Intercept response start to add routing token header
            if message["type"] == "http.response.start" and not has_added_token:
                has_added_token = True

                try:
                    # Extract authenticated user from scope state
                    # FastAPI/Starlette stores request state in scope["state"]
                    state = scope.get("state", {})
                    if isinstance(state, dict):
                        authed_user = state.get("user")
                    else:
                        # state might be a State object
                        authed_user = getattr(state, "user", None)

                    if authed_user:
                        # Generate routing token
                        uid = getattr(authed_user, "uid", None)
                        subscription_type = getattr(
                            authed_user, "subscription_type", "free"
                        )

                        if uid:
                            # Generate HMAC token
                            token = await self._generate_routing_token(
                                uid, subscription_type
                            )

                            if token:
                                # Add token to response headers
                                headers = list(message.get("headers", []))
                                headers.append(
                                    (b"x-routing-token", token.encode("utf-8"))
                                )
                                message["headers"] = headers

                                logger.debug(
                                    f"Added routing token for user {uid} "
                                    f"(tier={subscription_type})"
                                )

                except Exception as e:
                    # Log error but don't fail the request
                    logger.warning(f"Failed to generate routing token: {e}")

            # Always send the original message (possibly with modified headers)
            await send(message)

        # Process the request with our wrapped send function
        await self.app(scope, receive, send_wrapper)

    async def _generate_routing_token(self, uid: str, tier: str) -> Optional[str]:
        """
        Generate HMAC-SHA256 signed routing token.

        Token format: base64(uid|tier|timestamp|signature)
        - uid: Firebase user ID
        - tier: Subscription type (premium/free)
        - timestamp: Unix timestamp
        - signature: HMAC-SHA256(uid|tier|timestamp, secret_key)

        Args:
            uid: User ID (Firebase UID)
            tier: Subscription tier (premium/free)

        Returns:
            Base64-encoded signed token, or None if error
        """
        try:
            # Get secret key (with caching)
            secret_key = await self._get_secret_key()
            if not secret_key:
                logger.error("Failed to retrieve HMAC secret key")
                return None

            # Generate timestamp
            timestamp = int(datetime.utcnow().timestamp())

            # Create message to sign
            message = f"{uid}|{tier}|{timestamp}"

            # Generate HMAC signature
            signature = hmac.new(
                secret_key.encode(), message.encode(), hashlib.sha256
            ).hexdigest()

            # Combine message and signature
            token_data = f"{message}|{signature}"

            # Base64 encode
            token = base64.b64encode(token_data.encode()).decode()

            return token

        except Exception as e:
            logger.error(f"Error generating routing token: {e}")
            return None

    async def _get_secret_key(self) -> Optional[str]:
        """
        Get HMAC secret key from AWS Secrets Manager with caching.

        Uses in-memory cache with 5-minute TTL to reduce AWS API calls.
        Cache is shared across all requests in the same process.

        Returns:
            Secret key string, or None if retrieval fails
        """
        current_time = time.time()

        with _secret_key_cache["lock"]:
            # Check if cache is valid
            if (
                _secret_key_cache["key"]
                and current_time - _secret_key_cache["timestamp"] < _SECRET_CACHE_TTL
            ):
                return _secret_key_cache["key"]

        # Cache miss or expired - fetch from Secrets Manager
        try:
            # Run in thread pool to avoid blocking event loop
            loop = asyncio.get_event_loop()
            secret_key = await loop.run_in_executor(None, self._fetch_secret_from_aws)

            if secret_key:
                # Update cache
                with _secret_key_cache["lock"]:
                    _secret_key_cache["key"] = secret_key
                    _secret_key_cache["timestamp"] = current_time

            return secret_key

        except Exception as e:
            logger.error(f"Error fetching HMAC secret from Secrets Manager: {e}")
            return None

    def _fetch_secret_from_aws(self) -> Optional[str]:
        """
        Synchronous function to fetch secret from AWS Secrets Manager.
        Called in thread pool to avoid blocking the event loop.

        Returns:
            Secret key string, or None if retrieval fails
        """
        try:
            client = boto3.client("secretsmanager", region_name=self.aws_region)
            response = client.get_secret_value(SecretId=self.secret_name)

            # Parse secret JSON
            secret_json = json.loads(response["SecretString"])
            secret_key = secret_json.get("key")

            if not secret_key:
                logger.error(
                    f"Secret {self.secret_name} exists but 'key' field is missing"
                )
                return None

            logger.info("Successfully fetched HMAC secret from Secrets Manager")
            return secret_key

        except Exception as e:
            logger.error(
                f"Failed to fetch secret '{self.secret_name}' from Secrets Manager: {e}"
            )
            return None
