"""add dataview feature

Revision ID: 4df5949c42ef
Revises: 0b3a8e2ca9c1
Create Date: 2025-07-14 10:08:42.263790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4df5949c42ef"
down_revision = "0b3a8e2ca9c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "experiment_records",
        sa.Column(
            "publish_status",
            sa.Integer(),
            nullable=False,
            comment="0: private, 1: public",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
