name: Tests

on:
  pull_request:
    branches:
      - main
      - develop-main
      - develop-feature
      - develop-subscription
    paths-ignore:
      - "docs/**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run test_run command
        env:
          STRIPE_CALLBACK_URL: http://localhost:8000
        shell: bash
        run: |
          make test_run
